name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    name: Nix build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v8

    - name: Enable Nix Flakes
      run: |
        echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
        sudo systemctl restart nix-daemon || true

    - name: Build the flake
      run: nix build .#default --print-build-logs

    - name: Build the devShell
      run: nix develop --command echo "Dev shell works!"

  lint:
    name: Nix Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v8

    - name: Check Nix formatting
      run: |
        nix run nixpkgs#nixpkgs-fmt -- --check .

  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Go tests
      run: go test ./...
